/**
 * Pre-rendered audio — slice 8.
 *
 * THE ONLY MESSAGE YOU CANNOT SYNTHESISE IS THE ONE SAYING SYNTHESIS IS BROKEN.
 *
 * Bulbul is the single point of failure this architecture explicitly accepted
 * ([ADR 0005](../../docs/adr/0005-tts-provider-split.md)): there is no Indic TTS
 * failover anywhere in the stack, because no second Indic voice exists in either
 * provider. When it goes, the bot has nothing to say and no way to say it — which
 * is exactly the silent failure the speakability gate was built to prevent,
 * arriving from a different direction.
 *
 * So the apology is rendered ahead of time and shipped as bytes. Small, boring,
 * and the difference between a companion that explains itself and one that simply
 * stops existing mid-sentence.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * OPERATIONAL NOTE, because this is the failure mode of the mitigation itself:
 * these files are generated by `npm run render:holding`, which needs a WORKING
 * Bulbul. You cannot produce them during the outage they exist for. They must be
 * generated and committed ahead of time, and regenerated whenever the voice or
 * the copy changes — otherwise the outage apology arrives in a different voice
 * from the rest of the conversation, which is its own small horror.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * FORMAT: headerless linear16 PCM, mono, at TTS_SAMPLE_RATE — byte-identical to
 * what Bulbul streams, so the device path needs no special case. The manifest
 * records the rate it was rendered at; a mismatch is refused rather than played,
 * since the failure is otherwise a chipmunk apology.
 */

import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { REFUSAL_LADDER, SPEAKABLE, normalizeLanguage } from "../domain/languages.ts";
import type { LanguageCode, MessageKey } from "../domain/types.ts";

/** Any keyed line may be pre-rendered; only one of them has to be. */
export type HoldingKey = MessageKey;

/**
 * The clip that must exist. Everything else in the copy table can be synthesised
 * on demand, because on every other path TTS is by definition still working.
 */
export const REQUIRED_CLIPS: readonly HoldingKey[] = ["degraded.voice_unavailable"];

export type Manifest = {
  sample_rate: number;
  encoding: "linear16";
  speaker: string;
  rendered_at: string;
};

export type HoldingAudioOptions = {
  dir: string;
  /** Must match TTS_SAMPLE_RATE, or playback is refused. */
  expectedSampleRate: number;
  log?: ((level: string, msg: string, extra?: Record<string, unknown>) => void) | undefined;
};

export class HoldingAudio {
  readonly #clips = new Map<string, Buffer>();
  readonly #opts: HoldingAudioOptions;
  #manifest: Manifest | null = null;
  #usable = false;

  constructor(opts: HoldingAudioOptions) {
    this.#opts = opts;
  }

  get usable(): boolean {
    return this.#usable;
  }

  get manifest(): Manifest | null {
    return this.#manifest;
  }

  /**
   * Read everything at boot. Synchronous on purpose: these are a handful of small
   * files, and the alternative is discovering the directory is empty at the
   * precise moment we need it, on a path that by definition cannot recover.
   */
  load(): void {
    const { dir, expectedSampleRate, log } = this.#opts;

    if (!existsSync(dir)) {
      log?.("warn", "no pre-rendered holding audio", {
        dir,
        consequence: "a Bulbul outage will close sessions in silence rather than with an apology",
        fix: "npm run render:holding (needs a working Bulbul and a live key)",
      });
      return;
    }

    const manifestPath = join(dir, "manifest.json");
    if (existsSync(manifestPath)) {
      try {
        this.#manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as Manifest;
      } catch (err) {
        log?.("error", "holding audio manifest is unreadable", { err: String(err) });
        return;
      }
    }

    if (this.#manifest && this.#manifest.sample_rate !== expectedSampleRate) {
      // Refuse rather than play. Wrong-rate PCM is not a degraded apology, it is
      // a chipmunk, and that is worse than silence.
      log?.("error", "holding audio sample-rate mismatch — refusing to play it", {
        rendered_at_rate: this.#manifest.sample_rate,
        expected: expectedSampleRate,
        fix: "re-run npm run render:holding at the configured TTS_SAMPLE_RATE",
      });
      return;
    }

    for (const file of readdirSync(dir)) {
      // <message.key>.<language>.pcm  e.g. degraded.voice_unavailable.hi-IN.pcm
      if (!file.endsWith(".pcm")) continue;
      const stem = file.slice(0, -4);
      const at = stem.lastIndexOf(".");
      if (at === -1) continue;
      const key = stem.slice(0, at);
      const language = stem.slice(at + 1);
      try {
        this.#clips.set(cacheKey(key, language), readFileSync(join(dir, file)));
      } catch (err) {
        log?.("warn", "unreadable holding clip", { file, err: String(err) });
      }
    }

    this.#usable = this.#clips.size > 0;
    const missing = this.missing();
    if (missing.length > 0) {
      log?.("warn", "pre-rendered holding audio is incomplete", {
        have: this.#clips.size,
        missing: missing.length,
        first_missing: missing.slice(0, 5),
      });
    }
  }

  /**
   * Resolve a clip, falling down the refusal ladder rather than returning nothing.
   *
   * Same principle as the text copy: a missing Odia clip should produce a Hindi
   * apology, never silence. The ladder is the same one the speakability gate uses,
   * so a user who has heard us speak at all has heard one of these languages.
   */
  get(key: HoldingKey, language: LanguageCode): Buffer | null {
    const norm = normalizeLanguage(language);
    const candidates = [norm, ...REFUSAL_LADDER].filter((c): c is string => typeof c === "string");
    for (const c of candidates) {
      const hit = this.#clips.get(cacheKey(key, c));
      if (hit) return hit;
    }
    return null;
  }

  /** Every (clip, language) pair we expect and do not have. Surfaced at boot. */
  missing(): string[] {
    const out: string[] = [];
    for (const key of REQUIRED_CLIPS) {
      for (const lang of SPEAKABLE) {
        if (!this.#clips.has(cacheKey(key, lang.code))) out.push(`${key}.${lang.code}`);
      }
    }
    return out;
  }
}

function cacheKey(key: string, language: string): string {
  return `${key}|${language}`;
}
